language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
cache:
  - pip
  - yarn
install:
  - yarn install
  - pip install -r requirements.txt
  - python manage.py collectstatic --noinput
script: pytest
